### ISSUE TITLE
Install workflow for RNAseq

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/GalaxyKickStart#12]
And deposit workflow in a repository.

**Comment by mvdbeek** [comment]
Kind-of done, but for metavisitor
https://github.com/ARTbio/ansible-artimed/blob/master/group_vars/metavisitor

**Comment by mvdbeek** [comment]
We are doing this regularly now for metavisitor, have to check how well this is documented

**Comment by drosofff** [comment]
Well, actually it could be a use case for the application note
