### ISSUE TITLE
FTP to Metavisitor docker containers (or other flavors built with galaxykickstarter)

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#139]
Is indeed not easy at all. For instance the container running on the IFB 192.54.201.178, the "get data" by FTP return "localhost" as information to the user...

(used to work with a flat ansible-artimed installation)

**Comment by mvdbeek** [comment]
This is more complicated to get it right. You can use docker run -e "IP_ADDRESS=<the ip address you have>", but very often you actually want localhost, right? If we autodetect it, people might complain if they would actually want the localhost address, instead of the public IP address.

**Comment by mvdbeek** [comment]
I think the actionable item here is that we'll have to mention how to get the correct IP address in the documentation.
