### ISSUE TITLE
Automate building of flavors

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/GalaxyKickStart#143]
I see 2 ways to do this:
- We can regularly build a artbio/metavisitor:base image by hand, and then use this base image to create incremental builds. This should prevent timeouts on travis-ci.
- We can try to use conda as much as possible to install dependencies, which should accelerate the tool installation enormously. I think most tools already have conda dependencies, it's just sra-toolkit that needs to be ported to conda. Then we do not have this dependency on perl/gnu-coreutils anymore.

For me the 2nd option is the cleanest approach that would scale to more than just a handful of flavours,
but conda is a new feature ... it would need some testing.

**Comment by mvdbeek** [comment]
There is a third way, we can target an IFB instance after a successfull travis master merge. Something along the lines of triggering a `ssh user@ip nohup docker build -t metavisitor`. I guess we can store the ssh key as an encrypted value in the repo. In return we should probably abstract the test and build into a Makefile, so that we can share this between travis and the IFB instance.

**Comment by drosofff** [comment]
Wait a moment please.
What I am trying to do currently, is to update the available artbio/metavisitor-1.2 image on the Docker hub, for the _submission of the manuscript_.

So I need now your help to _understand_ whether as soon as my new build is ready, I can `push` to the Docker Hub (and then it will be on the top of the preexisting artbio/metavisitor-1.2:latest), or, if I have to `commit` something.

**Comment by mvdbeek** [comment]
> Wait a moment please.

This is in planning, I am not doing anything yet, and it's not very high in my priority list either, but it should be recorded, hence this issue.

> So I need now your help to understand whether as soon as my new build is ready, I can push to the Docker Hub (and then it will be on the top of the preexisting artbio/metavisitor-1.2:latest), or, if I have to commit something.

Nothing has changed, you can do what you would usually do, which I suppose is 

- docker build
- docker tag
- docker login
- docker push

If you want to preload the indexes manually, then it would be

- docker build
- docker run & index what you would like to be available
- docker commit
- docker tag
- docker login
- docker push
