### ISSUE TITLE
Script to generate gist for debugging

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/GalaxyKickStart#147]
so that we don't have to guess too much.

This should include the ansible_log, supervisor log, supervisor status, supervisor config file, galaxy.ini and /etc/default/supervisor.

**Comment by drosofff** [comment]
Could you clarify what you mean with "Script to generate gist". What does gist stand for ?

**Comment by mvdbeek** [comment]
gist.github.com -- just an example where you can paste logs.

**Comment by drosofff** [comment]
I know what is gist.github.com.
Yet I still don't understand the current issue. Please explain.

**Comment by mvdbeek** [comment]
Instead of users raising an issue that is missing all the important details, and where we need to guess or wair for a response we would ask for the logs, which could be collected with a single command (`get-logs`) and posted to gist.github.com (`post logs`).

**Comment by drosofff** [comment]
OK. Can I change the issue title to:
`Generate and post galaxykickstart install logs for better debugging`
?

**Comment by mvdbeek** [comment]
Sure

**Comment by mvdbeek** [comment]
Alternatively we could also provide a galaxy tool to do this. Which would of course not work if galaxy isn't starting ...

**Comment by drosofff** [comment]
:-) You vote against your own suggestion, don't you ?

**Comment by mvdbeek** [comment]
That wouldn't be the first time :). 
In theory this sounds like a good idea, but the more I think about it the more problems I see. How do we know where the current log files are, if the user has customized the path? 
Perhaps a separate play or role would be the most robust solution, plus we can intercept failures in ansible and run the debug role. That could even be nice to have for travis.
