### ISSUE TITLE
Rename ansible-artimed repo to GalaxyKickstarter

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#162]
Before doing this we need to carefully evaluate any potential issue with previously published links (github links, **documentation**, etc)

I did a test by renaming my forked ansible-artimed repo to GalaxyKickstarter.
But Marius, I would need clarification on how actually the readthedocs doc is generated in the ansible-artimed repo

**Comment by mvdbeek** [comment]
> But Marius, I would need clarification on how actually the readthedocs doc is generated in the ansible-artimed repo

The full procedure is in [deploy.sh](https://github.com/ARTbio/ansible-artimed/blob/master/deploy.sh):
```
mkdir -p docs/html
(
    cd docs/html
    git init
    git config user.name "${GH_USER_NAME}"
    git config user.email "${GH_USER_EMAIL}"
    git remote add upstream "https://$GH_TOKEN@${GH_REF}"
    git fetch upstream
    git reset upstream/gh-pages
)
```
We create a new docs/html directory, and clone the `gh-pages` branch in that directory.
```
cd $SCRIPT_PATH
mkdocs build --clean --site-dir docs/html
```
We then use mkdocs to build the documentation`

```
(
    cd docs/html
    touch .
    git add -A .
    git commit -m "Rebuild pages at ${rev}"
    git push -q upstream HEAD:gh-pages
)
```
And then we push the newly generated html docs to the gh-pages branch.

Travis is doing this at the end of a successful merge.

**Comment by drosofff** [comment]
Thanks, I figured out this week end indeed.
I am still not clear on the use of the git reset upstream/gh-pages command
... and also whether the html access would be affected in case of repo renaming. There is a note on this specific point, and GH advises to use and external domaine name in case or renaming.

**Comment by mvdbeek** [comment]
I would love for this to be renamed to GalaxyKickStart for the GCC. We can do this when the PlosOne review is back, right?

**Comment by drosofff** [comment]
Me too. yes. GalaxyKickStart

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-06-17 15:59 GMT+02:00 Marius van den Beek <notifications@github.com>:
