### ISSUE TITLE
ansible version and Travis testing

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#190]
- @mvdbeek would it be correct to replace https://github.com/ARTbio/GalaxyKickStart/blob/master/.travis.yml#L32
  by

```
git clone --recursive -b stable-2.1 https://github.com/ansible/ansible
pip install ansible/
```

since it is required to get the ansible-galaxy-tools working ?(https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/tasks/main.yml#L2)
- Then a question for my understanding of the GKS testing by Travis:
  Why is the test working in travis with pip installing ansible 2.1.1.0, when a manual testing of the PR #189 (just an example) works only with ansible 2.1.2.0 ?
  I mean, it seems that Travis is not currently really testing the repo code.

I remember that we discussed the issue, could you refresh my mind about it ?

**Comment by mvdbeek** [comment]
> @mvdbeek would it be correct to replace https://github.com/ARTbio/GalaxyKickStart/blob/master/.travis.yml#L32 by

Yes, you can do this. The reason that this doesn't fail for use is because we override the restart galaxy handler, so the [task include issue ](https://github.com/ansible/ansible/issues/15915) doesn't apply if we just use our own standard roles.
 (https://github.com/ARTbio/GalaxyKickStart/blob/master/galaxy.yml#L5)

> Then a question for my understanding of the GKS testing by Travis: Why is the test working in travis with pip installing ansible 2.1.1.0, when a manual testing of the PR #189 (just an example) works only with ansible 2.1.2.0 ? I mean, it seems that Travis is not currently really testing the repo code.

This is because of https://github.com/nturaga/GalaxyKickStart/blob/904eaf75346b48d5cf35225fcf05c761c2156f41/roles/cloud_setup/handlers/main.yml#L11

So travis is not complaining, because we are only testing the galaxy-kickstart standard setup (which doesn't include the new jetstream role).

**Comment by drosofff** [comment]
> So travis is not complaining, because we are only testing the galaxy-kickstart standard setup (which doesn't include the new jetstream role).

Are you sure ? because when testing the PR I first manually tested it the galaxy-kickstart standard setup (to check it was preserved in the PR), and it did not work until I upgraded ansible to 2.1.2.0. And also the error was clearly triggered by the ansible-galaxy-tool module which is used in galaxy-kickstart standard setup.

**Comment by mvdbeek** [comment]
> Are you sure ? because when testing the PR I first manually tested it the galaxy-kickstart standard setup (to check it was preserved in the PR), and it did not work until I upgraded ansible to 2.1.2.0. And also the error was clearly triggered by the ansible-galaxy-tool module which is used in galaxy-kickstart standard setup.

https://github.com/ARTbio/GalaxyKickStart/blob/master/dockerfiles/galaxy-kickstart/Dockerfile#L19

Sorry, we're already doing this in the correct place. So yes, it may be necessary to use 2.1.2.0

**Comment by drosofff** [comment]
Ok, thanks for checking

**Comment by drosofff** [comment]
Thus, I'll we do this after the PR#189 is merged, including the changes in the .Travis.yml and in the documentation that should state ansible 2.1.2.0 and the way to get it (through git and pip install) - If I understand correctly this is the only way, the apt build is 2.1.1.

This also connects to the discussion https://github.com/ARTbio/GalaxyKickStart/issues/143#issuecomment-216050145.

Correct me If I am wrong: Currently what is tested in Travis is a docker build of GalaxyKickStart. I understand that this tests the GalaxyKickStart code in large extent. But strictly speaking it does not test the GalaxyKickStart deployment in VM or physical machines. I can think about a bash script in `internals` to trigger 1 or several deployments on an IFB VM. Then moving this in a GH hook...

**Comment by mvdbeek** [comment]
Well, you'll have to have something listening to that github hook, and it
can't be travis, cause it will time out waiting for the response. But I
think we can use the Jenkins docker setup that John wrote for the
galaxy-community-qa project. So we could run a Jenkins server that will
spin on cloud machines on jetstream or the Ifb to test the deployment.

**Comment by drosofff** [comment]
First point addressed (ansible version).
Issue left open for automated testing not using travis
