### ISSUE TITLE
galaxy_config_dir variable

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#195]
in group_vars/all `galaxy_config_dir` is currently set to "{{ galaxy_data }}/config"
https://github.com/ARTbio/GalaxyKickStart/blob/master/group_vars/all#L13

Shouldn't we set it to "{{ galaxy_server_dir }}/config" instead ?

**Comment by mvdbeek** [comment]
yes, that is better.

**Comment by drosofff** [comment]
done in PR #196
