### ISSUE TITLE
Issue with the cloud_setup role

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#199]
Hi @afgane @mvdbeek 

I just failed to install artimed with GalaxyKickStart:

`ansible-playbook --inventory-file inventory_files/artimed galaxy.yml`

with the following error

```
TASK [cloud_setup : Install CernVM-FS keys] ************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'cvmfs_keys' is undefined"}
	to retry, use: --limit @/root/GalaxyKickStart/galaxy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=7    unreachable=0    failed=1
```

I suspect the upgrade of ansible because in previous logs, I found:

```
TASK [cloud_setup : Install CernVM-FS keys] ************************************
[91m[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this
 will be a fatal error.: 'cvmfs_keys' is undefined.
This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[0mskipping: [localhost]

TASK [cloud_setup : Perform AutoFS and FUSE configuration for CernVM-FS] *******
skipping: [localhost]

TASK [cloud_setup : Configure CernVM-FS domain] ********************************
[91m[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this
 will be a fatal error.: 'cvmfs_server_urls' is undefined.
This feature will be
 removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[0mskipping: [localhost]
```

Any thoughts ?

Best

**Comment by afgane** [comment]
I don't understand why this was happening at all - you had the role excluded, right? Further, why did it happen with `cvmfs_keys ` and not with `cvmfs_server_urls`?

**Comment by drosofff** [comment]
I only use the native galaxy.yml file of the repo, without any turn around. I assume that the exclusion is handled by the `when` instruction for this role in galaxy.yml.

With regard to why it happend with cvmfs_keys and not with cvmfs_server_urls I have no idea. But anyway the @mvdbeek fix works nice, I tested it manually. Not completely serene with the issue, which sounds like something that could show up again with ansible deprecations, but so far so good !

**Comment by mvdbeek** [comment]
> Further, why did it happen with cvmfs_keys and not with cvmfs_server_urls?

My take on this is that it would have also happened with cvmfs_server_urls, but that cvmfs_keys came first.

> I don't understand why this was happening at all - you had the role excluded, right?

I think the ansible folks decided that you must have all variables defined, even if you skip tasks ... hence the warning. If that's a good decision is another question ... .
The warning was pretty brutal and clear though, so it's our fault for not taking actions.
