### ISSUE TITLE
Local modifications to dependent roles

### ISSUE THREAD

**Issue by dustin-cram** [ARTbio/GalaxyKickStart#210]
I'm wondering if there is a recommended way to deal with local modifications to the dependent roles.  Since those are downloaded with the ansible-galaxy script as opposed to being cloned, any changes I might make to them can't easily be maintained/tracked.

Or are others generally not modifying these for in-house changes?

**Comment by mvdbeek** [comment]
We generally try to contribute any changes back to the upstream repo.
If you're testing locally you can just clone the roles in to the roles/ folder, those should take precedence over the remote roles.
If you would like to use a fork of GalaxyKickStart and you need to modify any of the roles, you can fork these roles and add them to the [requirements_roles.yml 
 file](https://github.com/ARTbio/GalaxyKickStart/blob/master/requirements_roles.yml)

**Comment by dustin-cram** [comment]
Thanks @mvdbeek ,

I've had to make a couple changes to some of the roles because (I think) I'm targeting Ubuntu 16.04, not 14.04.  I'll fork everything and adjust requirements_roles.yml as you suggest.

**Comment by mvdbeek** [comment]
We'd appreciate any Pull-requests for getting the roles working on 16.04 :).

**Comment by dustin-cram** [comment]
Yep, that's on my TODO list, right after - of course - making the fixes less ugly.

**Comment by drosofff** [comment]
Yep, thanks a lot.
FYI, I remember that setting the postgresql_version variable to 9.5 or something in group_vars/all helps for Ubuntu 16.04

**Comment by drosofff** [comment]
@dustin-cram if you don't mind, I think we can close the issue. see PR #232
