### ISSUE TITLE
move also /tmp when using galaxy.movedata role

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#219]
@mvdbeek would you mind if we add also
- { path: "/tmp" , owner: "root" }
after
https://github.com/ARTbio/GalaxyKickStart/blob/master/roles/galaxy.movedata/defaults/main.yml#L8
?
In some occasion the /tmp directory can get substantially large and with instances with small root volume it can be an issue. This occurs for instance when uploading large files to Galaxy
I am doing it routinely with IFB instances and it works without pb

**Comment by mvdbeek** [comment]
> In some occasion the /tmp directory can get substantially large and with instances with small root volume it can be an issue. This occurs for instance when uploading large files to Galaxy
> I am doing it routinely with IFB instances and it works without pb

why not use a variable to specify the upload directory [here](https://github.com/ARTbio/GalaxyKickStart/blob/master/group_vars/all#L77)?

**Comment by mvdbeek** [comment]
This is already available in ansible-galaxy-extras as `nginx_upload_store_path`. So if you change https://github.com/ARTbio/GalaxyKickStart/blob/master/group_vars/all#L77 to "{{ nginx_upload_store_path }}" and you set a default value in group_vars/all you can override this per deployment.

**Comment by drosofff** [comment]
Sure, if you're ok with nginx_upload_store = "/home/galaxy/galaxy/database/tmp" in group_vars/all

**Comment by drosofff** [comment]
Actually, this fails because galaxy does not have sufficient rights to write in /home/galaxy/galaxy/database/tmp/, which crashes supervisorctl galaxy:
The galaxy-extra role create the nginx_upload_store_path with root rights.
