### ISSUE TITLE
Debian - apt frequently crashes

### ISSUE THREAD

**Issue by colindaven** [ARTbio/GalaxyKickStart#242]
The ansible_module_apt.py on the Debian machine frequently freezes. Then you can't do anything with apt any more (error: fails to get a lock on the relevant apt files.

To solve this issue you can just kill the (crashed) ansible apt module:

ansible_module_apt.py 

Otherwise, restarting the machine helps of course.

E:Directory/var/lib/apt/lists/ cannot be locked.
root@debiantest:/galaxy_local/GalaxyKickStart# ps -aux | grep apt
root     16966  6.6  1.1 126952 70860 pts/2    S    12:11   0:03 /usr/bin/python /tmp/ansible_DD4XbB/ansible_module_apt.py
root     17009  0.2  0.2 171056 13092 pts/2    S    12:11   0:00 /usr/lib/apt/methods/https
root     17010  0.1  0.0  38924  5008 pts/2    S    12:11   0:00 /usr/lib/apt/methods/http
root     17011  0.0  0.0  38924  4880 pts/2    S    12:11   0:00 /usr/lib/apt/methods/http
root     17012  0.1  0.0  38924  4872 pts/2    S    12:11   0:00 /usr/lib/apt/methods/http
root     17015  0.1  0.0  28260  4296 pts/2    S    12:11   0:00 /usr/lib/apt/methods/gpgv
root     17021 13.0  0.0  28248  4312 pts/2    S    12:11   0:02 /usr/lib/apt/methods/copy
root     17028  0.1  0.0  28252  4544 pts/2    S    12:11   0:00 /usr/lib/apt/methods/bzip2
root     17032  0.0  0.0  12748  2108 pts/2    S+   12:11   0:00 grep apt

**Comment by drosofff** [comment]
@colindaven Is there anything we can do upstream ?

**Comment by colindaven** [comment]
Nope. We'll test further on more debian machines. Might be helpful for other users though.
