### ISSUE TITLE
nginx-upload-module for Debian

### ISSUE THREAD

**Issue by tglomb** [ARTbio/GalaxyKickStart#247]
Hi,

I'm trying to run GKS on Debian Jessie. 
After finishing the ansible run I checked the supervisor's info in my browser. There I can see that nginx isn't running and I cannot start it clicking the start button.
So I tried starting nginx manually and I got the error:

<code>nginx: [emerg] unknown directive "upload_store" in /etc/nginx/nginx.conf:127</code>

Then I checked the yaml files and found in GKS/roles/galaxyprojectdotorg.galaxy-os/tasks/ubuntu/packages.yml the two tasks
* "Add custom Galaxy PPA (used for nginx package)" and
* "Pin Galaxy's versions of the PPAs so they take priority over the defaults".

This part is missing in GKS/roles/galaxyprojectdotorg.galaxy-os/tasks/debian/packages.yml. It seems that the missing nginx-upload-store module keeps nginx from starting on Debian.

Is there a way to install that particular module on Debian?

Thanks in advance.

Torsten

**Comment by mvdbeek** [comment]
> Is there a way to install that particular module on Debian?

Unfortunately we will need to build nginx deb files for debian (we're doing the same for ubuntu actually). I will have a look, it shouldn't be too hard to do that.

**Comment by mvdbeek** [comment]
Args, so debian doesn't have something like launchpad where you can easily upload / build packages. I've build nginx by hand, and the build seem work, but that's less than ideal, since we can't automatically distribute the packages. It seems that we could abuse github pages to host debian packages through sth. like https://github.com/tsuru/tsuru-deb/issues/12.

**Comment by tglomb** [comment]
But there seems to be a way to use launchpad. In the installation instructions for Ansible is launchpad a [possibility for Debian users](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian). Pip is also mentioned as [alternative](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-pip).

Hope that helps. ;o)
