### ISSUE TITLE
playbook breaks on missing nginx file

### ISSUE THREAD

**Issue by seru71** [ARTbio/GalaxyKickStart#259]
I deployed GalaxyKickStart on a remote machine with Ubuntu 16.04 using artisan configuration. During the play ansible came across a missing file in nginx:
FAILED! => {"changed": false, "failed": true, "msg": "Source /usr/share/nginx/html/50x.html not found"}

This could be related to the particular version of nginx installed. After commenting out the task everything else worked smoothly.

**Comment by drosofff** [comment]
@seru71 OK, I noticed the error, I will address this asap. Thanks for reporting !

**Comment by drosofff** [comment]
@seru71 : the PR #260 is a (bit ugly) turnaround of the issue.
