### ISSUE TITLE
Byte-range request issues

### ISSUE THREAD

**Issue by luke-c-sargent** [ARTbio/GalaxyKickStart#262]
using the current master deploying to ubuntu 16.04, i am unable to make byte-range requests (so visualization in a place like UCSC Genome Browser doesn't function).

**expected** (from a live server deployed with an earlier version of GKS):
```
curl -I http://cloud5.galaxyproject.org/datasets/2210f6d255ed314c/display/
```
yields
```
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 Oct 2017 21:38:54 GMT
Content-Type: text/plain
Content-Length: 24817038
Last-Modified: Thu, 08 Jun 2017 22:42:06 GMT
Vary: Accept-Encoding
Set-Cookie: galaxysession=c6ca0ddb55be602aba9d34f21a464418adb8f05793401ee16e2bf3343361a204f3d0495bdebc0eaa; expires=Tue, 02-Jan-2018 21:38:54 GMT; httponly; Max-Age=7776000; Path=/; Version=1
ETag: "5949d2be-17aad8f"
Accept-Ranges: bytes
Age: 0
Via: 1.1 bladex.ohsu.edu
```

**actual**(from a test VM, but has also been tested on an AWS server):
```
curl -I http://192.168.56.160/datasets/f2db41e1fa331b3e/display/
```
yields
```
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 04 Oct 2017 21:44:04 GMT
Content-Type: application/octet-stream
Content-Length: 835708
Connection: keep-alive
x-frame-options: SAMEORIGIN
content-disposition: attachment; filename="Galaxy1-[unknown.2bit].twobit"
Set-Cookie: galaxysession=c6ca0ddb55be603a7003498f4abad2b4c00d6e639f051f933dfa47106c806ed991698fc649796d0b; expires=Tue, 02-Jan-2018 13:44:04 GMT; httponly; Max-Age=7776000; Path=/; Version=1
```

notably absent: `Accept-Ranges: bytes`

`curl -r` as expected provides requested bytes in the successful case, whereas it provides all bytes when using the version from master. I will continue to troubleshoot, but any suggestions to narrow my search scope are welcome. Thanks!

(there have been some recent changes to the galaxy-extras repo, that's where i am focusing my investigation)

**Comment by luke-c-sargent** [comment]
note: using an older version of the galaxyproject.galaxy-extras role (hash: f8cb73171030982e6a3ca5a98e4201544dacaa05) seems to have the same issue, implying it may not be a problem with that role.

**Comment by drosofff** [comment]
I'll have a close look asap. Thanks for reporting the issue

**Comment by luke-c-sargent** [comment]
another note to help guide troubleshooting: it doesn't appear as though it's the version of nginx at fault, as both versions of nginx specified [in the galaxy-os ansible role's packages task](https://github.com/galaxyproject/ansible-galaxy-os/blob/master/tasks/ubuntu/packages.yml) are able to serve byte-range requests when installed in isolation

**Comment by luke-c-sargent** [comment]
the first step of the playbook where byte range-requests can no longer be made is when supervisorctl is restarted after copying over templated conf files in `galaxyprojectdotorg.galaxy-extras`

**Comment by drosofff** [comment]
Hi @luke-c-sargent 
Is this still an open issue ?

**Comment by luke-c-sargent** [comment]
@drosofff this issue is indeed resolved; sorry about the delay!

**Comment by drosofff** [comment]
No problem thank for the update !
