### ISSUE TITLE
metavisitor-2 worflows 1-1, 1-2  and 1-3

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#301]
@ccedmendoza 
there is a slight "bug" in the new workflows: at the blastn alignment step, the parameter "maximum hit to report by alignment should be set at 5 instead of 0". Othewise, this causes the report of many more hits and the run time of cap3 to reassemble the hits increases dramatically (X 10).

By the way, I even think that this maximum value of 5 could be set to 1, if it is confirmed that this is the best hit for an alignment that is reported. but this probably would require extensive testing. In any case the max value of 5 for metavisitor 1-2 has always looked arbitrary, without clear rational

**Comment by drosofff** [comment]
@ccedmendoza shall we close this issue ?

**Comment by ccedmendoza** [comment]
Yes I think it can be closed
