### ISSUE TITLE
metavisitor-2 workflow 3-3

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#302]
@ccedmendoza Another problem with the new workflow for 3-3 use case:

It is interrupted at a blast alignment step (dataset 22), in your test as in mine. I think it is just a problem of reconnecting data collections with new tool version. At least I already saw this kind of issue before. Generally if you reassemble carrefully the workflow from scratch, it is fixed.

**Comment by drosofff** [comment]
shall we close this issue @ccedmendoza ?

**Comment by ccedmendoza** [comment]
Yes I think this issue can be closed
