### ISSUE TITLE
GPL license usage

### ISSUE THREAD

**Issue by luke-c-sargent** [ARTbio/GalaxyKickStart#327]
just wondering why GPL was chosen over, say, AFL (Galaxy's license). in our case, we forked GalaxyKickStart to tailor it to our specific flavor of Galaxy, but wanted to use AFL, and so were forced to rework how we used GKS.

no rush, a mere idle curiosity -- thanks!

**Comment by drosofff** [comment]
@luke-c-sargent I must say that I am not an expert in Licences.
But if you tell what AFL allows that GPL does not, I would be happy to consider a change in this matter (I even don't know if it is possible to change)

**Comment by luke-c-sargent** [comment]
I am far from an expert myself, but per [wikipedia](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#General_comparison), the key distinction is AFL's permissive linking, distribution and modification requirements vs. GPL's copyleft.

(per [wikipedia](https://en.wikipedia.org/wiki/Copyleft), copyleft is: "the practice of offering people the right to freely distribute copies and modified versions of a work with the stipulation that the same rights be preserved in derivative works created later.")

My understanding is that AFL allows other people to do whatever they want with the software, going so far as to allow commercial use -- GPL requires that derivative works be GPL'd (which is why we couldn't use AFL in a GalaxyKickStart fork).

At first glance it doesn't look like you need to use GPL (but again, I am far from an expert and my statements are far, _far_ from legal advice), but we've already done the aforementioned rework so we have no vested interest in what becomes of the license; just thought I'd ask. Thanks for the input!
