### ISSUE TITLE
Fixes for GalaxyKickStart

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#347]
Over the 6 last months many changes have been introduced in gks and a number of bugs escapes to automated testing with Travis.

We should address:

- [x] Upload is broken in the docker instance: work on the absence of _upload section in nginx.conf

- [ ] A more appropriate job_conf.xml for quick use of the docker instance. This is also an issue with ansible

- [ ] Slurm is not well working in the docker instance. Dig into this damned problem of supervisor in docker

- [x] Go back to use of the miniconda role for conda, since its drop off is probably responsible for the small bug at tool installation with the install-tool role

- [x] the dependency_resolvers_conf.xml file is not well installed, at least in 19.01
  ```
  galaxy.tools.deps DEBUG 2019-07-24 15:03:54,741 [p:3959,w:0,m:0] [MainThread] Unable to find config file './dependency_resolvers_conf.xml'
  ```

**Comment by drosofff** [comment]
I have some hopes that re-using miniconda role will fix many bugs, including the _upload issue...

**Comment by mvdbeek** [comment]
Didn't look into this at all, but you don't need `_upload` route in the nginx config or the nginx upload module anymore, Galaxy can now handle large uploads without that. When migrating away from that also make sure you don't have `nginx_upload_store` and `nginx_upload_path` set in the Galaxy config.
Hope that helps!

**Comment by drosofff** [comment]
Thanks for the tip @mvdbeek
