### ISSUE TITLE
slurm.log in the galaxy working dir belongs to root

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#53]
version d20e36af9753e4ef9c20367c4496c5bb431a6dda

seems a bit odd

**Comment by mvdbeek** [comment]
yes ... slurm is being run as root, so that's why it is owned by root. I agree about the location, and actually this should go directly to the supervisor logs.

**Comment by fabiorjvieira** [comment]
to fix this right we must propose a variable to set the user for slurm tasks in https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/supervisor.conf.j2 (lines between 15 and 30, tag user). ;)

**Comment by mvdbeek** [comment]
I don't really think so, we should just not redirect the stdout, so that supervisor can properly log this.
but that's a discussion to have an ansible-galaxy-extras
