### ISSUE TITLE
Fork and track upstream roles for ARTbio in a sustainable manner

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/GalaxyKickStart#62]
Edit: We should move this away from my personal account.

As discussed with @drosofff, it's a good idea to have the external roles as backup, in case they disappear.

I'll do it manually for now, and then we could use a crontab to keep this up-to-date.

**Comment by mvdbeek** [comment]
OK, all roles in use are forked under the ARTbio account.

**Comment by fabiorjvieira** [comment]
If the original repo is deleted, the fork will not disappear?

**Comment by mvdbeek** [comment]
No, it is a real (copy-on-write) copy.

**Comment by mvdbeek** [comment]
I stuck this script in my crontab:
https://gist.github.com/mvdbeek/37b77326e6921f963993

with this are updating or forks every 2 hours.

**Comment by mvdbeek** [comment]
@drosofff so you want to run this on the server (mississippi?)  then?
The issue is that is we would need to create a bot that does just the synchronization, since I don't want to put my credentials on the server. Not hard to do, but also not high in my priority list.

**Comment by drosofff** [comment]
Yes not in the priority list. good to mark it through.

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-06-19 12:47 GMT+02:00 Marius van den Beek <notifications@github.com>:
