### ISSUE TITLE
Actually the doc does not indicate how to install tools and workflows

### ISSUE THREAD

**Issue by drosofff** [ARTbio/GalaxyKickStart#90]
in https://github.com/ARTbio/ansible-artimed/blob/master/docs/installing%20tools%20and%20workflows.md#installing-tools

the command to run to ultimately install tools and workflows is not indicated

**Comment by mvdbeek** [comment]
I'd consider this an artefact of how we used the role in the beginning (install_tools: yes/no, run_extras: yes/no ... ).
We should probably state that for each and every change you should run the full playbook, and that if you know what you are doing you can jump to specific sections using tags.

**Comment by drosofff** [comment]
Mmmm. The principle of a getting started doc is definitely not to say that
you have just to know what you are doing. We must accompany the user as far
as it is reasonable. And it's seems to me that it is reasonable to give the
procedure to install, metavisitor, for instance.

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-03-18 13:07 GMT+01:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
> Mmmm. The principle of a getting started doc is definitely not to say that
> you have just to know what you are doing.

I think if you came in with a fresh in

**Comment by mvdbeek** [comment]
We also have to put the difference between tool_panel_section_label and tool_panel_section_id, plus the  the `-skip_id` and `--get_latest` flags to get_tool_yml_from_gi.py

**Comment by drosofff** [comment]
Can you say it in english please ? I am not in your mind :-)


Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-03-18 19:30 GMT+01:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
Sorry, that's just  a reminder for me to incorporate those details at the correct place in the documentation, it comes down to [this](https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample)
```
...
# Further, you need to provide **one** of the following two keys:
#  * tool_panel_section_id: ID of the tool panel section where you want the
#                           tool to be installed. The section ID can be found
#                           in Galaxy's `shed_tool_conf.xml` config file. Note
#                           that the specified section must exist in this file.
#                           Otherwise, the tool will be installed outside any
#                           section.
#  * tool_panel_section_label: Display label of a tool panel section where
#                              you want the tool to be installed. If it does not
#                              exist, this section will be created on the target
#                              Galaxy instance (note that this is different than
#                              when using the ID).
#                              Multi-word labels need to be placed in quotes.
#                              Each label will have a corresponding ID created;
#                              the ID will be an all lowercase version of the
#                              label, with multiple words joined with
#                              underscores (e.g., 'BED tools' -> 'bed_tools').
...
```
 And with the get_tool_yml_from_gi.py script you have options to only get the most recent changeset revision of a tool, and to not output the `tool_panel_section_id`

```
  -l, --get_latest      Include only latest revision of a repository in
                        tool_list.yml ?
  -skip_id, --skip_tool_panel_id
                        Do not include tool_panel_id in tool_list.yml ?
```

So I don't know how you made tool list in PR #93 , but I guess the this would have been useful information.

**Comment by drosofff** [comment]
Yes, definitely. I was planing to dig into the code of get_tool_yml_from_gi.py to implement at least the second option :)

**Comment by mvdbeek** [comment]
This is now easier with the new scripts in extra-files/get_tool_list_from... , need to document this.
